
DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_INCL  = $(DEPTH)/include/unit_tests
MODULE_NAME  = tests
LIBRARY_NAME = test_strings
MODULE_EXT   = exe

MODULE_FILES=test_strings.cpp

DM_UTILITIES:=1

include $(topsrcdir)/config/rules.mk
