#

DEPTH= ../..

include $(DEPTH)/config/config.mk

MODULE_NAME = cci

XPIDL_MODULE = xpcci_io

IDLSRC = cciIStreams.idl \
         cciIFileStreams.idl \
         cciIMemoryInputStream.idl \
         $(NULL)


include $(topsrcdir)/config/rules.mk
